version: 2
jobs:

  build:
    working_directory: ~/$CIRCLE_PROJECT_REPONAME
    docker:
      - image: debian:latest
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build
          command: docker build .

workflows:
  version: 2

  deploy:
    jobs:
      - build
