version: 2
jobs:

  build:
    working_directory: ~/docker-network-agent
    docker:
      - image: node:10.6
    steps:
      - checkout
      - run: npm install

workflows:
  version: 2

  deploy:
    jobs:
      - build
