version: 2
jobs:

  test:
    working_directory: ~/docker-network-agent
    docker:
      - image: node:10.6
    steps:
      - checkout
      - run: npm install
      - run:
          name: Test
          command: npm test

workflows:
  version: 2

  Test:
    jobs:
      - test
